name: Build VSIX

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-build-
      
      - run: npm ci
      
      - run: npm run build
      
      - name: Create VSIX
        run: npx vsce package
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      
      - uses: actions/upload-artifact@v3
        with:
          name: vsix-package
          path: '*.vsix'